version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app_network

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - app_network

  web:
    build: .
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/restaurant_management_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - DJANGO_CACHE_LOCATION=memcached:11211
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
