version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app_network

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - app_network

  restaurant_app:
    build: .
    volumes:
      - .:/restaurant_management_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
    environment:
      - TESTING=False 
      - DJANGO_SETTINGS_MODULE=restaurant_management.settings
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - DJANGO_CACHE_LOCATION=memcached:11211
    command: >
      bash -c "
        if [ \"$TESTING\" == 'True' ]; then 
          python manage.py migrate --noinput;
          python manage.py test;
        else 
          python manage.py runserver 0.0.0.0:8000;
        fi"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
